### ISSUE TITLE
Implement Optional Compression Methods in Cluster Constructor

### ISSUE THREAD

**Issue by Daniel-Boll** [Daniel-Boll/scylla-javascript-driver#1]
**Overview**:
This issue proposes the enhancement of adding optional compression methods to the `Cluster` constructor, aligning with the Scylla Rust Driver's capabilities as documented [here](https://rust-driver.docs.scylladb.com/stable/connecting/compression.html). The feature should allow users to specify their preferred compression (LZ4, Snappy, or None) when establishing a connection to a Scylla cluster.

**Detailed Behavior**:
The new feature will expand the `Cluster` constructor's functionality by introducing a `compression` parameter. This parameter will accept an enum, `Compression`, that includes the options `NONE` (default), `LZ4`, and `SNAPPY`. The specified compression algorithm will be used in the communication between the driver and Scylla nodes, potentially reducing network traffic and improving performance, especially when large volumes of data are being transferred.

**Proposed Implementation**:
The implementation will leverage `napi-rs` to bridge the Rust Scylla driver's capabilities with Node.js. Here's a preliminary look at how the API might be structured:

```typescript
import { Cluster, Compression } from "@lambda-group/scylladb";

const cluster = new Cluster({
  nodes: ["127.0.0.1:9042"],
  compression: Compression.LZ4, // options: Compression.NONE (default), Compression.LZ4, Compression.SNAPPY
});
```

Assignees and Mentions:
- TBD depending on who is interested or has the relevant expertise. '@' mention or assign the issue to them.

Progress/Updates:
- This is the initial issue creation. Updates will follow as discussions proceed, decisions are made, and implementation begins.

**Comment by f0ntana** [comment]
@Daniel-Boll let me try it!

**Comment by Daniel-Boll** [comment]
You've been selected for the task, @f0ntana. Should you encounter any uncertainties or have any concerns, please don't hesitate to reach out to me. Together, we'll collaborate effectively to address any issues and ensure a successful outcome.

Daniel Boll. 🎴
