### ISSUE TITLE
Query feature: PreparedStatement (Not Fully Documented Issue)

### ISSUE THREAD

**Issue by Daniel-Boll** [Daniel-Boll/scylla-javascript-driver#12]
# TODO

I still need to document this issue

https://rust-driver.docs.scylladb.com/stable/queries/prepared.html

**Comment by f0ntana** [comment]
@Daniel-Boll assign this to me!

**Comment by DanielHe4rt** [comment]
@f0ntana you took almost a year to finish it :p 

Implemented a simple version in the #23 PR

**Comment by felipe-palazzo** [comment]
> @f0ntana you took almost a year to finish it :p
> 
> Implemented a simple version in the #23 PR

Yeap, I stopped working on it!
